### ISSUE TITLE
int32 Read register error

### ISSUE THREAD

**Issue by jemarr** [rkl099/Appinventor-Modbus#1]
Hi.

I'm using your extension in AI2 to read the Modbus data of an SMA inverter with modbusTCP. My problem is that there are some registers with int32 bit format and then I get an -2 error. Single 16 bit registers are read fine.

Would you implement some kind of parameter to choose the register size ???

Thanks for your great work.

**Comment by rkl099** [comment]
Error code -2 means that you don’t get a response of correct length.
Modbus specification v1.1 does not specify a 32 bit transfer. I should have expected that you could read a 32 bit register as two separate 16 bit reads. My guess mow is that you need to read a 32 bit register as 2 16bit registers in one transfer (which is not implemented) or a user specific function code if this does not work. Maybe the user manual of your converter can clarify it?

**Comment by jemarr** [comment]
Yes, I must read a 32 bit register or two consecutive 16 bit.

The SMA inverter manual specify that the register is in int32 format.

This is what I get with a Modbus TCP tester:

![image](https://user-images.githubusercontent.com/22809959/161397904-9600e6ff-fea7-428e-8c00-7571421ed668.png)

**Comment by jemarr** [comment]
Would you try to implement some mod to make the extension working ? .... please !!!

**Comment by rkl099** [comment]
Set length to 1 and try to read first 16 bit address 0, then do the same for address 1, to see if its possible to read 32 bit as two separate 16bit registers in two separate transfers.

**Comment by jemarr** [comment]
If i put 1 in length I got a timeout error:

![image](https://user-images.githubusercontent.com/22809959/161398188-28828587-7533-4252-a219-d1327fe4fcaa.png)

if I put 2 in length its ok:

![image](https://user-images.githubusercontent.com/22809959/161398214-3b460a0f-7a85-4459-ba9d-8ca63cc35c59.png)

**Comment by jemarr** [comment]
Anf If I increment the register +1 and length set to 1 I get an incorrect value:

![image](https://user-images.githubusercontent.com/22809959/161398309-358c2b9a-8d6e-4980-9170-421ab8873945.png)

**Comment by rkl099** [comment]
OK, i understand. You need to transfer 32bit as one transfer of two 16 bit registers, as your example with length 2, address 0.
I have to think if and how  this can be implemented. Can you tell me if registers values 0000, 0182 should be read as 00000182 or 01820000?

**Comment by jemarr** [comment]
00000182

**Comment by jemarr** [comment]
so first byte MSB

**Comment by rkl099** [comment]
OK

**Comment by jemarr** [comment]
Thanks for your time !!!

**Comment by rkl099** [comment]
I have added a new function ReadDoubleHoldingReg() that can be used just as ReadSingleHoldingReg(). ResponseSingle() shall now return 32bit from two 16bit holding registers in sequence. I also tried to update my test program. I have no way to test it right now, so please try it and return. The new version can be found at Appinventor_Debug directory. 
Made an error in the test program. APK updated.

**Comment by jemarr** [comment]
Hi....

I've tested the extension and it's working fine !!!! thanks !!!!

Tomorrow I'll test more in depth with more registers but I think it will be ok.

I've tested the new Modbus.apk and it doesn't works, it gives me an error -3 with the same registers. Nevertheless the extension updated in my simple test program works like a charm.

Thanks again.

**Comment by rkl099** [comment]
Nice to hear. Here are the error codes from ResponseSingle:

-1 No serial open
-2 TCP format error or no response
-3 RTU format error or no response
-4 RTU crc error
-5 Unknown function code or nr of bytes error

**Comment by jemarr** [comment]
I've tested it and it's running fine. Thanks again.

If I want to read three registers (not consecutive) at the same time how can I do to avoid clock timers interferences from one response to the others ?

**Comment by rkl099** [comment]
Modbus TCP has an transaction identifier that can be used for this purpose, but it's not implemented in this extension, and it's not always used in the devices you connect to. So you have to wait for the response or timeout. You can use function Available() to see that you got a message of proper length instead of waiting for timeout before testing the response, to speed things up.

**Comment by jemarr** [comment]
Ok... I understood.

Thanks
